### ISSUE TITLE
완주하지 못한 선수

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#13]
문제 설명
수많은 마라톤 선수들이 마라톤에 참여하였습니다. 단 한 명의 선수를 제외하고는 모든 선수가 마라톤을 완주하였습니다.
마라톤에 참여한 선수들의 이름이 담긴 배열 participant와 완주한 선수들의 이름이 담긴 배열 completion이 주어질 때, 완주하지 못한 선수의 이름을 return 하도록 solution 함수를 작성해주세요.

제한사항
- 마라톤 경기에 참여한 선수의 수는 1명 이상 100,000명 이하입니다.
- completion의 길이는 participant의 길이보다 1 작습니다.
- 참가자의 이름은 1개 이상 20개 이하의 알파벳 소문자로 이루어져 있습니다.
- 참가자 중에는 동명이인이 있을 수 있습니다.

**Comment by rose6649** [comment]
#include <string>
#include <vector>

using namespace std;

string solution(vector<string> participant, vector<string> completion) {
    //마라톤 참여한 선수들 배열 par
    //완주한 선수들 이름 담긴 배열 com
    //completion 길이 = participant - 1
    //참가자 이름 1-20 개 의 알파벳 소문자 이루어짐
    //동명이인있을수 있는 가능성
    int count = 0;
    
    
    for(int i = 0; i < participant.count(); i++) {
        int index = 
    }
    while(participant.size() > count) {
        bool flag = false;
        for(int i = 0; i < completion.size(); i++) {
            if(participant[count] == completion[i]) {
                completion[i].erase();
                flag = true;
                break;
            }
        }
        if(!flag) {
            return participant[count];
        }
        count++;
    }
    
    
}



- 처음 시작은 녹록치않았다. 이 코드는 정확도가 100이 나올수밖에 없지만
효율성 측면에서는 0점짜리 코드다.
왜냐면 참가자와 완주자의 모든 수를 돌아야하기때문.
즉, 최악인 경우에는 O(n*n)이 나올 수 있다.
사실 이 코드는 효율성없이 그냥 쓴 코드이다.

**Comment by rose6649** [comment]
```
#include <string>
#include <vector>
#include <map>

using namespace std;

string solution(vector<string> participant, vector<string> completion) {
    map<string, int> m;
    int count = 0;
    
    for(int i = 0; i < completion.size(); i++) {
        int count = m[completion[i]];
        m[completion[i]] = count + 1;
    }
    
    while(participant.size() > count) {
        if(m.count(participant[count]) == 0) {
            return participant[count];
        }
        else {
            if(m[participant[count]] > 0) {
                m[participant[count]] -= 1;
            }
            else {
                return participant[count];
            }
        }
        count++;
    }
    
    
}
```

- 해시문제라고 떡하니 써져있는 것을 활용하여 이중 반복문은 피해야겠다.
생각했다. 어쨌든 한번은 N번 도는건 어쩔수 없다고 봤고 그러면 한번만 반복문을 도는 방법을 생각하다가
해쉬 테이블 -> map, ordered_map STL이 생각이 났다.
map은 한쌍의 key, value로 이루어진다.
key를 이용하여 value을 O(1)에 찾을 수 있다. 뭐.. 최악의경우를 빼고는?
map은 일단, 라이브러리를 쓰긴 썼지만 균형트리(balance tree)로 이루어지며, 그 중에서도 red-black트리로 구현되어있다.
red-black트리가 뭐냐면, 일단 이진탐색트리를 알아야 한다. 이 적흑트리도 이진탐색트리이기때문에...
이진탐색트리는 특정 key값에 대한 탐색, 삽입, 삭제가 가능한 자료구조이다.
따라서, 왼쪽 서브트리에는 현재노드의 key 값보다 작은 것이 나오며, 오른쪽 서브트리는 큰게 나온다.

red-black트리는 "균형" 이진탐색트리로 되어있는데, 서치 연산은 O(logn)의 시간복잡도가 된다.
1. Root Property : 루트노드의 색깔은 검정(Black)이다.
2. External Property : 모든 external node들은 검정(Black)이다.
3. Internal Property : 빨강(Red)노드의 자식은 검정(Black)이다. No Double Red(빨간색 노드가 연속으로 나올 수 없다.) 
4. Depth Property : 모든 리프노드에서 Black Depth는 같다. 
조건을 만족해야 하며, 이 속성을 가진 map을 사용하니

결국 n+logn 시간이니 , O(n) 시간복잡도를 가지게 될것. (while문에서 참가자는 바로 탐색을 끝내버림. 한번더 도는 이유가 사라진다는 것!)

오랜만에 하니까 좀 시간이 걸렸다...
swift만 다루다보니까 C++ 코딩할 때 뒤에 세미콜론 자꾸 안찍고 if문에 가로 안넣고 해서 번거롭더라,,
역시 습관은 무서워!

**Comment by Minimoa** [comment]
## keypoint

- 선수 참가자 이름을 key로 몇번 나오는지 카운트한 값을 value로 딕셔너리를 만든다.
- 완주한 선수의 value를 -1 한다. 
- 완주했을 경우 +1 -1 이므로 0이 되고 완주 못했을 경우 1로 값이 남아 있게 된다. (동명이인의 경우도 마찬가지)

  

## python

```python
import collections 

def solution(participant, completion):
    answer = ''
    dict_p = collections.defaultdict(int) 
    
    for p in participant:
        dict_p[p] += 1
        
    for c in completion:
        dict_p[c] -= 1  
    
    for key in dict_p:
        if dict_p[key] == 1:
            answer = key
            break
    return answer
```

collections.Counter을 쓰면 바로 카운트 하여 dictionary를 만들 수 있다. 

```python
dict_p  = collections.Counter(participant)
# Counter({'leo': 1, 'kiki': 1, 'eden': 1})
```



## c++

```c++
#include <string>
#include <vector>
#include <map>

using namespace std;

string solution(vector<string> participant, vector<string> completion) {
    string answer = "";
    map<string,int> m;
    
    for(int i=0;i<participant.size();i++){
        if(m.find(participant[i]) != m.end()){
            m[participant[i]]+= 1;
        }else{
            m.insert({participant[i],1});
        }
    }
    
    for(int i=0;i<completion.size();i++){
        string c = completion[i];
        m[c] -= 1;
    }
    
    for(auto iter : m){
        if(iter.second == 1)
            answer = iter.first;
    }
    return answer;
}
```



c++은 따로 딕셔너리가 없어서 map STL을 찾아서 썼다. 

- 값 찾기 

  `if(m.find(participant[i]) != m.end())`

- insert

  `m.insert({key,value});`

- 반복문

  iterator.first -> key , iterator.second -> value

  - 범위 기반

    ```c++
    for(auto iter = m.begin();iter!=m.end();iter++)
    	cout<<iter->first <<" "<< iter->second<<"\n";
    ```

  - 인덱스 기반

    ```c++
     for(auto iter : m){
            cout<< iter.first <<" "<< iter.second 
        }
    ```

    

C++은 맵보다는 정렬을 사용한 방법이 더 간단한 것 같다. 

- 이름은 영문 대소문자라고 했으므로 정렬해서 반복문을 돌면서 participant , completion 배열을 비교해서 이름이 다른 경우 리턴
- 반복문에서 해결되지 않은 경우 participant 의 맨 마지막 원소가 답이므로 맨 마지막 원소 리턴  (completion 길이는 participant 보다 1 작다고 했으므로)



algorithm을 이용해서 다음과 같이 vector를 정렬할 수 있다. 

```c++
#include <algorithm>
sort(participant.begin(), participant.end());
sort(completion.begin(), completion.end());
```
