### ISSUE TITLE
전화번호 목록

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#14]
문제 설명
전화번호부에 적힌 전화번호 중, 한 번호가 다른 번호의 접두어인 경우가 있는지 확인하려 합니다.
전화번호가 다음과 같을 경우, 구조대 전화번호는 영석이의 전화번호의 접두사입니다.

- 구조대 : 119
- 박준영 : 97 674 223
- 지영석 : 11 9552 4421

전화번호부에 적힌 전화번호를 담은 배열 phone_book 이 solution 함수의 매개변수로 주어질 때, 어떤 번호가 다른 번호의 접두어인 경우가 있으면 false를 그렇지 않으면 true를 return 하도록 solution 함수를 작성해주세요.

제한 사항
- phone_book의 길이는 1 이상 1,000,000 이하입니다.
- 각 전화번호의 길이는 1 이상 20 이하입니다.

**Comment by rose6649** [comment]
```
#include <string>
#include <vector>
#include <algorithm>


using namespace std;

bool solution(vector<string> phone_book) {
    
    sort(phone_book.begin(), phone_book.end());
   
    for(int i=0; i<phone_book.size()-2; i++) {
        if(phone_book[i+1].find(phone_book[i]) == 0) {
            return false;
        }
    }
    return true;
}
```

음, 이부분은 map으로 풀려하였으나, 그렇게되면 O(n^2)시간복잡도를 피할 수 없어서 고민을 많이 했다.
저건 효율성측면으로 계속 오바날 것 같고, 그렇다면 방법을 달리해보자.
사실 완주하지못한 선수에서 정인이의 꿀팁을 얻었다. sort라는 방법이 있구나!
해서, 바로 생각해낸게 vector을 sort하여 어짜피 한 인덱스 값이 그 전 인덱스값을 포함하고 있으면, 그게 false로 바로 결정지을 수 있으니까
이 방법이 최선이었던 것 같다.
sort()는 기존 우리가 알고 있는 quick sort 알고리즘을 사용한다.
퀵소트는 분할 정복 (divide and conquer) 알고리즘 중 하나이고, 오름차순으로 정렬한다.
이는 O(nlogn) 시간복잡도를 가지게 되는데, 최악의 경우에는 O(n^2)로 나타낼 수 있다 한다.
그래도 우리의 STL인 sort()는 최악의 경우 n^2가 안나오게 구현되어있다.
이 최악의 경우는 (1) 정렬되어있거나 (2) 역순으로 정렬되어있거나 인데, 아마 이를 바로 캐치할 코드를 더 보완했던것같다.

**Comment by Minimoa** [comment]
## solving point

배열을 오름차순으로 정렬하면 접두사가 되는 전화번호가 배열의 0번에 오게 된다 (제일 짧으니까)

나머지 전화번호에서 0번째 전화 번호 길이 만큼을 비교해서 같을 경우 false, 아니면 true 



## python

```python
def solution(phone_book):
    answer = True
    phone_book.sort() 
    prefix = phone_book[0]
    
    for p in phone_book[1:] :
        if prefix == p[:len(prefix)] :
            answer = False
            return answer
    return answer
```



sort - > O(nlogn)

총 O(nlogn)

 

### 알게된 방법

zip을 이용하면 startswith 함수를 쓸 수 있다.  알고리즘은 똑같지만 코드가 더 간단하다

```python
for p1, p2 in zip(phoneBook, phoneBook[1:]):
	if p2.startswith(p1):
            return False
return False
```

**zip**

2개의 리스트를 한번에 for문 돌리고 싶을때 써먹자

자료형이 다른 리스트들을 묶어서 딕셔너리를 만들때에도 유용함

```python
Number = [1,2,3,4]
Name = ['hong','gil','dong','nim']
dic = {}
for number , name in zip(Number,Name): 
    dic[number] = name
print(dic)
'''
결과 : {1 : 'hong' , 2 : 'gil' , 3 : 'dong' , 4 : 'nim'}
'''
```





## C++

```c++
#include <string>
#include <vector>
#include <algorithm>  

using namespace std;

bool solution(vector<string> phone_book) {
    sort(phone_book.begin(),phone_book.end());
    string prefix = phone_book[0];
    int len = prefix.size();
    
    for(int i=1;i<phone_book.size();i++){
        string comp = phone_book[i].substr(0,len); 
        if(comp == prefix)
            return false;
    }
    
    return true;
}
```

 

똑같은 방법 

C++ 문자열 길이 

`.size()`

C++ 문자열 자르기

`substr(0,len)`

까먹지 말기!
