### ISSUE TITLE
위장

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#15]
문제 설명
스파이들은 매일 다른 옷을 조합하여 입어 자신을 위장합니다.

예를 들어 스파이가 가진 옷이 아래와 같고 오늘 스파이가 동그란 안경, 긴 코트, 파란색 티셔츠를 입었다면 다음날은 청바지를 추가로 입거나 동그란 안경 대신 검정 선글라스를 착용하거나 해야 합니다.
스파이가 가진 의상들이 담긴 2차원 배열 clothes가 주어질 때 서로 다른 옷의 조합의 수를 return 하도록 solution 함수를 작성해주세요.

제한사항
- clothes의 각 행은 [의상의 이름, 의상의 종류]로 이루어져 있습니다.
- 스파이가 가진 의상의 수는 1개 이상 30개 이하입니다.
- 같은 이름을 가진 의상은 존재하지 않습니다.
- clothes의 모든 원소는 문자열로 이루어져 있습니다.
- 모든 문자열의 길이는 1 이상 20 이하인 자연수이고 알파벳 소문자 또는 '_' 로만 이루어져 있습니다.
- 스파이는 하루에 최소 한 개의 의상은 입습니다.

**Comment by rose6649** [comment]
```
#include <string>
#include <vector>
#include <map>
using namespace std;


int solution(vector<vector<string>> clothes) {
    map<string, int> m;
    int total=1;
    
    for(int i=0; i<clothes.size(); i++) {
        if(m.count(clothes[i][1]) == 0) {
            m[clothes[i][1]] = 1;
        }
        else {
            m[clothes[i][1]] += 1;
        }
    }
    
    for(auto iter: m) {
        total *= (iter.second + 1);
    }
    
    return total - 1;
    //m의 size는 종류별 사이즈
    //m의 key에 대한 value값은 그 key의 개수
}
```

음, 여기서 사용한 알고리즘은 map을 이용한 조합? 정도밖에 없다.
어쨌든 시간복잡도는 모든 값을 한번씩 탐색하니 O(n)이 될것이며, 조합을 위해 key, value에 맞는 조건들을 써주면 된다.
나는 key: 의상의 종류, value: 그 의상의 개수 로 나타내었다.
이렇게하면, 의상의종류에 대한 (의상개수+1) 를 다 곱해주면된다. 그러고나서, 아무것도안입었을때는 없기때문에 -1를 마지막으로 해준다.!
여기는 효율성측면은 따로 검사안하더라..

**Comment by Minimoa** [comment]
## solving point 

적어도 하나 선택한다고 했으니까 전체 경우에서 하나도 선택하지 않을 경우를 뺀다.

전체 경우는 각 종류 +1 을 모두 곱하면된다 (곱의 법칙, 각 종류에서 하나씩 선택) 

1을 더하는 이유는 안 입는 경우까지 포함하기 때문

## python

```python
def solution(clothes):
    answer = 1
    closet = {}
    for c in clothes :
        closet.setdefault(c[1],0)
        closet[c[1]] += 1
    
    for v in closet.values():
        answer *= v+1
        
    answer -= 1
    return answer
```



이런 방법도 있다.

```python
cnt = Counter([kind for name, kind in clothes])
answer = reduce(lambda x,y: x*(y+1), cnt.values(),1)-1
```



## C++

```c++
#include <string>
#include <vector>
#include <map>
using namespace std;

int solution(vector<vector<string>> clothes) {
    int answer = 1;
    map<string,int> m;
    
    for(int i=0;i<clothes.size();i++){
        string kind = clothes[i][1];
        if(m.find(kind)!=m.end())
            m[kind] += 1;
        else
            m.insert({kind,2});
    }
    
    for(auto iter:m){
        answer *= iter.second; 
    }
    answer -= 1;
    return answer;
}
```



해쉬라기 보다는 수학 문제 

순열 조합 생각 안나서 헤맸다 ㅠ
