### ISSUE TITLE
주식가격

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#17]
문제 설명
초 단위로 기록된 주식가격이 담긴 배열 prices가 매개변수로 주어질 때, 가격이 떨어지지 않은 기간은 몇 초인지를 return 하도록 solution 함수를 완성하세요.

제한사항
- prices의 각 가격은 1 이상 10,000 이하인 자연수입니다.
- prices의 길이는 2 이상 100,000 이하입니다.

**Comment by rose6649** [comment]
```
#include <string>
#include <vector>
#include <stack>

using namespace std;

vector<int> solution(vector<int> prices) {
    vector<int> answer(prices.size());
    stack<pair<int,int>> s;
    int length = prices.size();
    s.push(make_pair(prices[0], 0));

    for(int i=1; i<prices.size(); i++) {
        while(length-1 == i || prices[i] < s.top().first) {
            if(length-1 == i && s.empty()) {
                break;
            }
            answer[s.top().second] = i - s.top().second;
            s.pop();
            if(s.empty()) {
                break;
            }
        }
        if(length-1 == i) {
            break;
        }
        s.push(make_pair(prices[i],i));
    }
    
    return answer;
}
```

아직도 흐름형 코드 . .
구성도면에서 너무 낮다. 조금 더 연습해야지..
여기서 쓰인 STL은 stack이다. stack은 제일 처음에 들어온게 제일 나중에 나오는 형태로, FILO? 라고 할수 있겠다.

일단 주어진 답은 vector형태고, 받는 인자도 vector형태다.
prices는 각각 다 종속되어있는 배열이며, 값이 하나씩 들어올수록, 그보다 작은 값이면 앞에는 수가 일정하게 +1 씩 증가해야 한다. (1초씩 더해야하므로)
그래서 들어오는 값에 맞춰 그 시간으로부터 초를 세야하는데, 그 값이 스택에 들어있는값보다 작을 때, 스택에 들어있는 값들은 반환되어야 한다. (가격이 떨어졌으므로)
index에 맞게 몇초동안 가격이 안떨어졌는지 세야한다. 그래서 index를 따로 stack에 pair로 두고 second값에 넣었다.

시간복잡도는 일단 prices 배열 만큼 (n) 돌고, 그 안에서 while문은 값에 맞춰 지금 들어온 수보다 스택에있는값이 클 경우들을 모두 pop한다.
pop하는 경우는, 총합쳐서 n만큼 pop하게 된다.
그러니까 최대로는, n만큼 도는데 거기서 n+n가 최대치기때문에, (while문은 논리적으로 상수시간걸린다.)
O(n)이라고 할 수 있다.

**Comment by Minimoa** [comment]
## solving point

answer에 총 시간을 역순으로 저장해놓는다 

(각 시점마다 유지되는 시간을 세팅해 놓기 위해서 )

큐에서 하나씩 꺼내고 나머지 값들과 비교한다 

만약 꺼낸 값이 더 크면 answer의 해당 인덱스에서  answer의 비교 인덱스 값을 빼서 업데이트한다 



## python

### 처음시도

```python
from collections import deque
def solution(prices):
    answer = [i for i in range(len(prices)-1,-1,-1)]
    idx = 0 
    deq = deque(prices)
    while len(deq)>1: 
        cur = deq.popleft() 
        if cur > deq[0]:
            answer[idx] -= answer[idx+1]
        idx+=1
    return answer
```

난리남

문제는 이 부분 

```python
if cur > deq[0]:
    answer[idx] -= answer[idx+1]
```



### 최종

```python
from collections import deque
def solution(prices):
    answer = [i for i in range(len(prices)-1,-1,-1)]
    idx = 0 
    deq = deque(prices)
    
    while len(deq): 
        cur = deq.popleft() 
        changed = idx+1  
        for d in deq :
            if cur > d :
                answer[idx] -= answer[changed]
                break
            changed+=1
        idx +=1
    return answer
```



deque의 popleft 는 O(1) 이다. 그냥 리스트로 pop(0)하면 O(n)이므로  효율적이지 못하다





## C++

STL 큐를 써보려고 했지만 탐색이 안된다고 해서 그냥 이중 포문 돌려서 풀었다 

```c++
#include <string>
#include <vector> 

using namespace std;

vector<int> solution(vector<int> prices) {
    vector<int> answer;  
    
    for(int i=prices.size()-1;i>=0;i--)
        answer.push_back(i);
    
    for(int i=0;i<prices.size();i++){
        for(int j=i+1;j<prices.size();j++){
            if(prices[i]>prices[j]){
                answer[i] -= answer[j];
                break;
            }
        }
    }
    return answer;
}
```

**Comment by dlwnsdud0704** [comment]
`#include <string>
#include <vector>
#include <queue>

using namespace std;

vector<int> solution(vector<int> prices) {
    vector<int> answer;
    vector<int> ans;
    answer = prices;
    priority_queue <pair<int,int>> pq;
    for(int i=0;i<prices.size();i++)
    {
        while(1)
        {
            if( !pq.empty()&&pq.top().first > prices[i] )
            {
                answer[pq.top().second]=i - pq.top().second;
                pq.pop();
            }
            else
            {
                break;
            }
        }
        pq.push({prices[i],i});
    }
    while(!pq.empty())
    {
        answer[pq.top().second] = prices.size() - pq.top().second -1;
        pq.pop();
    }
    return answer;
}`

우선순위 큐를 써서 풀었다.
pair {가격, 인덱스} 순서로 큐를 생성했다.

첫번째 for문에서는 
이러면 가격이 높고 인덱스가 높은 순서대로 큐가 생성되는데 
두`#include <string>
#include <vector>
#include <queue>

using namespace std;

vector<int> solution(vector<int> prices) {
    vector<int> answer;
    vector<int> ans;
    answer = prices;
    priority_queue <pair<int,int>> pq;
    for(int i=0;i<prices.size();i++)
    {
        while(1)
        {
            if( !pq.empty()&&pq.top().first > prices[i] )
            {
                answer[pq.top().second]=i - pq.top().second;
                pq.pop();
            }
            else
            {
                break;
            }
        }
        pq.push({prices[i],i});
    }
    while(!pq.empty())
    {
        answer[pq.top().second] = prices.size() - pq.top().second -1;
        pq.pop();
    }
    return answer;
}`

우선순위 큐를 써서 풀었다.
pair {가격, 인덱스} 순서로 큐를 생성했다.
이러면 가격이 높고 인덱스가 높은 순서대로 큐가 생성된다

첫번째 for문에서는 
우선순위큐 pq에 주식 값들을 저장하면서 저장된 주식값보다 떨어진경우 pop하면서 몇초가 걸렸는지 answer에 넣어준다.

마지막 while문에서는 가격이 떨어지지 않은 시점들의 시간들을 answer에 넣어준다.

사용한 testcase
[1, 2, 3, 4, 3, 2, 4, 3]  => [7,6,3,1,1,2,1,0]
