### ISSUE TITLE
다리를 지나는 트럭

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#19]
문제 설명
트럭 여러 대가 강을 가로지르는 일 차선 다리를 정해진 순으로 건너려 합니다. 모든 트럭이 다리를 건너려면 최소 몇 초가 걸리는지 알아내야 합니다. 트럭은 1초에 1만큼 움직이며, 다리 길이는 bridge_length이고 다리는 무게 weight까지 견딥니다.
※ 트럭이 다리에 완전히 오르지 않은 경우, 이 트럭의 무게는 고려하지 않습니다.

예를 들어, 길이가 2이고 10kg 무게를 견디는 다리가 있습니다. 무게가 [7, 4, 5, 6]kg인 트럭이 순서대로 최단 시간 안에 다리를 건너려면 다음과 같이 건너야 합니다.

경과 시간 | 다리를 지난 트럭 | 다리를 건너는 트럭 | 대기 트럭
-- | -- | -- | --
0 | [] | [] | [7,4,5,6]
1~2 | [] | [7] | [4,5,6]
3 | [7] | [4] | [5,6]
4 | [7] | [4,5] | [6]
5 | [7,4] | [5] | [6]
6~7 | [7,4,5] | [6] | []
8 | [7,4,5,6] | [] | []

따라서, 모든 트럭이 다리를 지나려면 최소 8초가 걸립니다.

solution 함수의 매개변수로 다리 길이 bridge_length, 다리가 견딜 수 있는 무게 weight, 트럭별 무게 truck_weights가 주어집니다. 이때 모든 트럭이 다리를 건너려면 최소 몇 초가 걸리는지 return 하도록 solution 함수를 완성하세요.

제한 조건
- bridge_length는 1 이상 10,000 이하입니다.
- weight는 1 이상 10,000 이하입니다.
- truck_weights의 길이는 1 이상 10,000 이하입니다.
- 모든 트럭의 무게는 1 이상 weight 이하입니다.

**Comment by rose6649** [comment]
```
#include <string>
#include <vector>
#include <queue>

using namespace std;

int solution(int bridge_length, int weight, vector<int> truck_weights) {
    int time = 0;
    int totalweight = 0;
    queue<int> q;
    queue<int> cross;
    
    for(int i =0; i<truck_weights.size(); i++) {
        q.push(truck_weights[i]);
    }
    
    for(int i =0; i<bridge_length; i++) {
        cross.push(0);
    }
    
               
    while(!(cross.empty())) {
        
        if(q.size() == 0) {
            cross.pop();
            time++;
            continue;
        }
        
        int w = q.front(); //트럭무게
        int first = cross.front();
        cross.pop();
        totalweight -= first;
        
        //다리 무게보다 트럭무게가 더 크면
        if(weight < totalweight + w) {
            cross.push(0);
        }
        //다리무게랑 트럭무게랑 같거나 작으면
        else {
            cross.push(w);
            q.pop();
            totalweight += w;
        }
        time++;
    }
        
        
    
    
    return time;
}
```

시간복잡도 생각하다가, 괜히 시간 낭비 많이 한 문제..
그냥 메모리나, 시간복잡도 생각안하고 직관적으로 풀었는데 100점맞았다.
이 방법이 제일 빠른 방법이었던가...
일단, 1초에 다리위에 트럭이 한번씩 움직인다. 트럭들은 다리의 무게를 넘을수없고, 이를 생각했을때
다리를 넘는 큐, 대기큐가 있어야할 것 같아서 q와 cross queue을 선언했다.
중간에, 트럭이 무게가 넘쳐 들어오지 못할 때는 그냥 cross 큐에 무게가 0인 순서를 넣었다. 이렇게 해야 순서대로 언제 공백이 있는지 알 수 있을테니까. 이거때문에 많은 고민을 했는데, 굳이 0을 넣어야할까, 다른 방법이 없을까. Index을 따로 맞게 해주면 또 정렬해야하고 값 올려야하고 힘들겠는데. 막 그랬는데
이게 제일 최선인것같다.

시간복잡도는 10,000이 일단 수가 최대기 때문에 이를 n으로 생각하면
각 큐에 수를 넣어줘야하므로, n만큼 2번 더해준다.
그다음 while문에서 트럭이 지나가는 시간을 구해야하는데,
일단 n만큼은 무조건 돌게 되고, 최악으로 따진다면 다리길이가 10000인데 트럭들이 다 무게가 10000인 경우. 그리고 그 트럭들의 개수가 10000인 경우.
이렇게되면 1초에 한번씩 움직일수있으니까 10000 * 10000 이 최악이 된다.
그런데 이런 상황까지는 잘 안올것같다.
O(n^2)

**Comment by Minimoa** [comment]
## sloving point 

bridge_length만큼 0을 넣은 bridge 큐를 만든다 

시간을 카운트한다 

큐에서 하나씩 꺼내서 현재 무게에서 뺀다  (birdge를 건넌 트럭이기 때문에)

- 대기 트럭에서 맨 앞의 값을 체크해서 현재 값과 더했을때 weight를 초과하지 않으면 

  대기 트럭에서 꺼내고 bridge에 올린다, 현재 무게에 꺼낸 트럭의 무게를 더해준다 

- weight 값을 넘으면 

  bridge에 더 이상 올릴 수 없지만 진행 중인 트럭이 있기 때문에 더미 데이터인 0을 넣어서 간격을 체크할 수 있도록 한다 





## python 



```python
from collections import deque
def solution(bridge_length, weight, truck_weights):
    time = 0
    bridge = deque([0]*bridge_length)
    trucks = deque(truck_weights)
    cur_weight = 0
    
    while bridge :
        time += 1
        tmp = bridge.popleft() 
        cur_weight -= tmp
        if trucks :
            if cur_weight + trucks[0] <= weight:
                tmp2 = trucks.popleft()
                bridge.append(tmp2)
                cur_weight += tmp2
            else :
                bridge.append(0)
    return time
```



쓸데 없이 위치에 집착해서 다리 건너기를 완료한 트럭을 어떻게 체크할 건지를 고민하다가 시간 낭비한 문제 

진행되는 흐름을 이해하기 !



## C++



```c++
#include <string>
#include <vector>
#include <queue>
using namespace std;

int solution(int bridge_length, int weight, vector<int> truck_weights) {
    int time = 0;
    queue<int> bridge;
    queue<int> trucks;
    int cur_weight = 0;
        
    for(int i=0;i<bridge_length;i++)
        bridge.push(0);
    
    for(int i=0;i<truck_weights.size();i++)
        trucks.push(truck_weights[i]);
    
    while(!bridge.empty()){
        time++;
        int tmp = bridge.front();
        bridge.pop();
        cur_weight -= tmp;
        if(!trucks.empty()){
            if(cur_weight + trucks.front() <= weight){
                int tmp2 = trucks.front();
                trucks.pop();
                cur_weight += tmp2;
                bridge.push(tmp2);
            }else{
                bridge.push(0);
            }
        }
    }
    
    return time;
}
```

**Comment by dlwnsdud0704** [comment]
```
#include <string>
#include <vector>
#include <queue>

using namespace std;

int solution(int bridge_length, int weight, vector<int> truck_weights) {
    int answer = 0;
    queue <pair<int,int>> q;
    int truck_num = 0;
    while(1)
    {
        if(answer - q.front().first == bridge_length && !q.empty())
        {
            weight += truck_weights[q.front().second]; 
            if(q.front().second == truck_weights.size()-1)
            {
                break;
            }
            q.pop();
        }
        if(weight - truck_weights[truck_num] >=0)
        {
            weight -= truck_weights[truck_num];
            q.push({answer,truck_num});
            truck_num++;
        }
        answer++;
    }
    return answer+1;
}
```

현재 다리위의 무게 = weight
다리위에있는 트럭 queue = q{트럭이 올라간 시간, 트럭}
answer는 시간으로 while이 한번 돌때마다 ++해줬다.
truck_num = 마지막으로 올라간 트럭number

트럭이 하나 올라갈때마다 weight 값에서 트럭무게를 빼서 다리에 올라갈수 있는 weight를 제한했다.
시간을 1초씩 더하면서 트럭을 올릴수 있으면 올리고 queue 맨앞에 있는 트럭이 빠져나갈시간이 되면 빼줬다.
마지막으로 트럭이 빠져나갔을때의 시간을 return해줬다.
마지막 answer+1은 처음 트럭이 올라갔을때의 시간이 0초라서 해줬다.
