### ISSUE TITLE
프린터

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#20]
문제 설명
일반적인 프린터는 인쇄 요청이 들어온 순서대로 인쇄합니다. 그렇기 때문에 중요한 문서가 나중에 인쇄될 수 있습니다. 이런 문제를 보완하기 위해 중요도가 높은 문서를 먼저 인쇄하는 프린터를 개발했습니다. 이 새롭게 개발한 프린터는 아래와 같은 방식으로 인쇄 작업을 수행합니다.

1. 인쇄 대기목록의 가장 앞에 있는 문서(J)를 대기목록에서 꺼냅니다.
2. 나머지 인쇄 대기목록에서 J보다 중요도가 높은 문서가 한 개라도 존재하면 J를 대기목록의 가장 마지막에 넣습니다.
3. 그렇지 않으면 J를 인쇄합니다.
예를 들어, 4개의 문서(A, B, C, D)가 순서대로 인쇄 대기목록에 있고 중요도가 2 1 3 2 라면 C D A B 순으로 인쇄하게 됩니다.

내가 인쇄를 요청한 문서가 몇 번째로 인쇄되는지 알고 싶습니다. 위의 예에서 C는 1번째로, A는 3번째로 인쇄됩니다.

현재 대기목록에 있는 문서의 중요도가 순서대로 담긴 배열 priorities와 내가 인쇄를 요청한 문서가 현재 대기목록의 어떤 위치에 있는지를 알려주는 location이 매개변수로 주어질 때, 내가 인쇄를 요청한 문서가 몇 번째로 인쇄되는지 return 하도록 solution 함수를 작성해주세요.

제한사항
- 현재 대기목록에는 1개 이상 100개 이하의 문서가 있습니다.
- 인쇄 작업의 중요도는 1~9로 표현하며 숫자가 클수록 중요하다는 뜻입니다.
- location은 0 이상 (현재 대기목록에 있는 작업 수 - 1) 이하의 값을 가지며 대기목록의 가장 앞에 있으면 0, 두 번째에 있으면 1로 표현합니다.

**Comment by rose6649** [comment]
```
#include <string>
#include <vector>
#include <queue>

using namespace std;

int solution(vector<int> priorities, int location) {
    priority_queue<int> pq;
    queue<pair<int,int>> q;
    int answer = 0;
    
    for(int i =0; i<priorities.size(); i++) {
        q.push(make_pair(priorities[i], i));
        pq.push(priorities[i]);
    }
    
    while(!(q.empty())) {
        pair<int,int> index = q.front();
        if(index.first == pq.top()) {
            if(index.second == location) {
                answer++;
                break;
            }
            q.pop();
            pq.pop();
            answer++;
        }
        else {
            q.pop();
            q.push(make_pair(index.first, index.second));
        }
    }
    
    
    return answer;
}
```

여기서 FIFO가 필요하기도하고, 우선순위도 필요하여 우선순위큐와 큐를 선언했다.
중요도가 똑같은 거라면 이 index 순이 priority queue의 정렬과는 좀 달라 따로 큐로 값을 정렬했다.
먼저 q에는 문제설명과 같이, 문서가 인덱스순으로 나열되게 넣었다.
그리고 우선순위큐는 우선순위에 맞게 순위가 높은거부터 나올 수 있도록 내림차순이 디폴트기때문에 그렇게 선언했다.
그렇게되면, 큐는 무조건 제일 높은 수가 제일 먼저 나가야하기 때문에, 우선순위큐와 비교하면서 pop을 해서 다시 뒤로 push했다.

음,,, 시간복잡도를 구하면 pq가 push될 때 자연적으로 정렬 처리가 되기때문에 이 시간이 생기는데,
보통 priority queue는 힙으로 구현되어있다. 기본적으로 최대힙으로 정렬되게 하며, 힙은 완전 이진 트리이다.
우선순위큐의 push의 시간복잡도는 최대 높이까지 올라가 정렬되게 만들 수 있으므로, O(logn)이다.
그렇다면 n*logn이 되겠고.
while문은 비교만하면되므로,
최종적으로 시간복잡도는 O(nlogn) 시간이 걸린다.

**Comment by Minimoa** [comment]
## solving point

현재 위치를 같이 묶어서 큐를 만든다  원래 배열은 내림차순으로 정렬한다

큐에서 맨 앞을 꺼낸다

만약 원래 배열 맨 앞의 우선순위가 더 높으면 맨 뒤에 넣는다

만약 큐에서 꺼낸 값이 더 크면 그냥 나간다 

만약 우선순위가 같으면 원래 배열에서도 꺼낸 후 



만약 꺼낼때 문서의 location이 요청한 location이면 종료



## python

```python
from collections import deque
def solution(priorities, location):
    answer = 0
    que = deque() 
    
    for [i,v] in enumerate(priorities):
        que.append([i,v])
    
    priorities.sort(reverse=True)
    prior = deque(priorities)
     
    while que:
        tmp = que.popleft() 
        if tmp[1] < prior[0]:
            que.append(tmp)  
        elif tmp[1] == prior[0]:
            prior.popleft()
            answer+=1 
            
            if tmp[0] == location :
                return answer
        else:
            answer+=1 
            
    return answer
```

**Comment by dlwnsdud0704** [comment]
```
#include <string>
#include <vector>
#include <queue>
#include <algorithm>

using namespace std;

int solution(vector<int> priorities, int location) {
    int answer = 0;
    queue<pair<int,int>> q;
    priority_queue<int> pq;
    for(int i=0;i<priorities.size();i++)
    {
        if(location == i)
        { 
            q.push({priorities[i],1});
        }
        else
        {
            q.push({priorities[i],0});
        }
        pq.push(priorities[i]);
    }
    int tmp = 1;
    while(!q.empty())
    {
        if(pq.top() == q.front().first)
        {
            if(q.front().second == 1)
            {
                answer = tmp;
                break;
            }
            q.pop();
            pq.pop();
            tmp++;
        }
        else
        {
            int tmp1 = q.front().first;
            int tmp2 = q.front().second;
            q.pop();
            q.push({tmp1,tmp2});
        }
    }
    return answer;
}
```

priority_queue를 사용해서 가장 높은 우선순위를 찾고 인쇄요청들을 queue에 넣고 내가 찾고싶은 인쇄만1로 표시해주었다.
그리고 무식하게 가장높은 우선순위가 앞으로 나올때까지 queue를 빼고 넣고를 반복했다.
