### ISSUE TITLE
더 맵게

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#21]
문제 설명
매운 것을 좋아하는 Leo는 모든 음식의 스코빌 지수를 K 이상으로 만들고 싶습니다. 모든 음식의 스코빌 지수를 K 이상으로 만들기 위해 Leo는 스코빌 지수가 가장 낮은 두 개의 음식을 아래와 같이 특별한 방법으로 섞어 새로운 음식을 만듭니다.

> 섞은 음식의 스코빌 지수 = 가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2)

Leo는 모든 음식의 스코빌 지수가 K 이상이 될 때까지 반복하여 섞습니다.
Leo가 가진 음식의 스코빌 지수를 담은 배열 scoville과 원하는 스코빌 지수 K가 주어질 때, 모든 음식의 스코빌 지수를 K 이상으로 만들기 위해 섞어야 하는 최소 횟수를 return 하도록 solution 함수를 작성해주세요.

제한 사항
- scoville의 길이는 2 이상 1,000,000 이하입니다.
- K는 0 이상 1,000,000,000 이하입니다.
- scoville의 원소는 각각 0 이상 1,000,000 이하입니다.
- 모든 음식의 스코빌 지수를 K 이상으로 만들 수 없는 경우에는 -1을 return 합니다.

**Comment by rose6649** [comment]
```cpp
#include <string>
#include <vector>
#include <queue>

using namespace std;

int solution(vector<int> scoville, int K) {
    int answer = 0;
    priority_queue<int, vector<int>, greater<int>> rank_scoville;
    for(int i=0; i <scoville.size(); i++) {
        rank_scoville.push(scoville[i]);
    }
    
    while(!(rank_scoville.empty())) {
        int first = rank_scoville.top();
        if(first < K) {
            if(rank_scoville.size() == 1) {
                answer = -1;
                break;
            }
            rank_scoville.pop();
            int second = rank_scoville.top();
            rank_scoville.pop();
            int mix = first + (second * 2);
            rank_scoville.push(mix);
            answer++;
        }
        else {
            break;
        }
    }
    
    
    return answer;
}
```

가볍게 풀었던 문제.
k가 좀 큰수라 당황했지만 별반 다른건 없더라.
우선순위큐를 사용한 이유는, 정렬되어있는 형태가 중요했기 때문이다. 그리고 힙을 사용하는 자료구조이기도 하고.
가장 작은 수부터 차례로 K와 비교해야하는데, 이를 오름차순 우선순위큐로 표현했다.
이 큐는 push할 때마다 logn시간이 걸리고,
이게 n만큼 Push을 하기때문에 O(nlogn) 시간이 걸린다.
while문은 계속 pop해주는 경우니, pop은 O(1)이므로, n시간만 걸린다.
따라서 총 O(nlogn)걸림.

**Comment by Minimoa** [comment]
## solving point

 최소힙을 사용하여 스코빌지수를 정렬한다. 

앞에서 두개를 꺼내서 섞는다 

```
가장 맵지 않은 음식의 스코빌 지수 + (두 번째로 맵지 않은 음식의 스코빌 지수 * 2)
```

다시 힙에 넣는다 

반복하여 만약 힙의 맨 처음이 K보다 클 수 없으면 -1 , K보다 크면 섞은 횟수를 리턴한다



K보다 클 수 없는 경우는 어떤 경우인지? 

모든 원소를 다 섞어서 하나 남았는데도 K보다 작을 경우 

## python

```python
import heapq

def solution(scoville, K):
    answer = 0 
    heapq.heapify(scoville) 
    
    while len(scoville) >= 2 : 
        first = heapq.heappop(scoville)
        second = heapq.heappop(scoville)
        heapq.heappush(scoville,first+(second*2))
        answer+=1 
        if scoville[0] >= K :
            return answer 
    
    if scoville[0] < K :
        answer = -1
    return answer
```



list를 heap으로 만들기

`heapq.heapify(scoville) `

heap에 push, pop 

`heapq.heappush(scoville,first+(second*2))`, `heapq.heappop(scoville)` 

무조건 맞았겠지 하는 생각으로 처음 돌렸을때 마지막 케이스만 틀려서 띠용했는데 scoville 길이가 2일때를 체크하지 않아서 그런 거였다. 주어진 조건이 몇 이상인지 이하인지 체크하는 것을 빼 먹지 말것!



## C++

 

```c++
#include <string>
#include <vector>
#include <queue>
#include <functional>

using namespace std;

int solution(vector<int> scoville, int K) {
    int answer = 0;
    priority_queue<int> pq;
    
    for(int i=0;i<scoville.size();i++)
        pq.push(-1 * scoville[i]);
    
    while(pq.size()>=2){
        int first = pq.top();
        pq.pop();
        int second = pq.top();
        pq.pop();
        pq.push(first+(second*2));
        answer++;
        if(-(pq.top()) >= K )
            return answer;
    }
    
    if (-(pq.top()) < K)
        answer = -1;
    
    
    return answer;
}
```



우선순위큐를 이용했다. 우선 순위큐는 기본으로 내림차순이므로 -1을 붙여서 오름차순이 될 수 있도록 했다. 우선순위큐는 front()가 아니라 top()인데 자꾸 헷갈림

우선 순위큐는 힙으로 구성되어 있고 힙은 완전 이진트리이므로 pq만드는데 nlogn, 반복문에서 삽입,삭제하는데 nlogn이므로 총 O(nlogn)이다
