### ISSUE TITLE
디스크 컨트롤러

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#22]
문제 설명
하드디스크는 한 번에 하나의 작업만 수행할 수 있습니다. 디스크 컨트롤러를 구현하는 방법은 여러 가지가 있습니다. 가장 일반적인 방법은 요청이 들어온 순서대로 처리하는 것입니다.

예를들어

- 0ms 시점에 3ms가 소요되는 A작업 요청
- 1ms 시점에 9ms가 소요되는 B작업 요청
- 2ms 시점에 6ms가 소요되는 C작업 요청

와 같은 요청이 들어왔습니다. 이를 그림으로 표현하면 아래와 같습니다.
한 번에 하나의 요청만을 수행할 수 있기 때문에 각각의 작업을 요청받은 순서대로 처리하면 다음과 같이 처리 됩니다.

- A: 3ms 시점에 작업 완료 (요청에서 종료까지 : 3ms)
- B: 1ms부터 대기하다가, 3ms 시점에 작업을 시작해서 12ms 시점에 작업 완료(요청에서 종료까지 : 11ms)
- C: 2ms부터 대기하다가, 12ms 시점에 작업을 시작해서 18ms 시점에 작업 완료(요청에서 종료까지 : 16ms)

이 때 각 작업의 요청부터 종료까지 걸린 시간의 평균은 10ms(= (3 + 11 + 16) / 3)가 됩니다.
하지만 A → C → B 순서대로 처리하면

- A: 3ms 시점에 작업 완료(요청에서 종료까지 : 3ms)
- C: 2ms부터 대기하다가, 3ms 시점에 작업을 시작해서 9ms 시점에 작업 완료(요청에서 종료까지 : 7ms)
- B: 1ms부터 대기하다가, 9ms 시점에 작업을 시작해서 18ms 시점에 작업 완료(요청에서 종료까지 : 17ms)
이렇게 A → C → B의 순서로 처리하면 각 작업의 요청부터 종료까지 걸린 시간의 평균은 9ms(= (3 + 7 + 17) / 3)가 됩니다.

각 작업에 대해 [작업이 요청되는 시점, 작업의 소요시간]을 담은 2차원 배열 jobs가 매개변수로 주어질 때, 작업의 요청부터 종료까지 걸린 시간의 평균을 가장 줄이는 방법으로 처리하면 평균이 얼마가 되는지 return 하도록 solution 함수를 작성해주세요. (단, 소수점 이하의 수는 버립니다)

제한 사항
- jobs의 길이는 1 이상 500 이하입니다.
- jobs의 각 행은 하나의 작업에 대한 [작업이 요청되는 시점, 작업의 소요시간] 입니다.
- 각 작업에 대해 작업이 요청되는 시간은 0 이상 1,000 이하입니다.
- 각 작업에 대해 작업의 소요시간은 1 이상 1,000 이하입니다.
- 하드디스크가 작업을 수행하고 있지 않을 때에는 먼저 요청이 들어온 작업부터 처리합니다.

**Comment by rose6649** [comment]
```cpp
#include <string>
#include <vector>
#include <queue>
#include <algorithm>

using namespace std;

int solution(vector<vector<int>> jobs) {
    sort(jobs.begin(), jobs.end());
    priority_queue<pair<int,int>, vector<pair<int,int>>, greater<pair<int,int>>> pq;
    int time = 0;
    int averagetime = 0;
    int count = 0;
    
    time = jobs[0][1] + jobs[0][0];
    averagetime = jobs[0][1];
    count++;
    
    while(count < jobs.size()) {
        
        if(jobs[count][0] > time) {
            time = jobs[count][0];
            continue;
        }
        
        while(jobs[count][0] <= time) {
            pq.push(make_pair(jobs[count][1], jobs[count][0]));
            count++;
            if(count >= jobs.size()) {
                break;
            }
        }
        
        while(!(pq.empty())) {
            averagetime += pq.top().first + (time - pq.top().second);
            time += pq.top().first;
            pq.pop();
            if(count >= jobs.size()) {
                    continue;
            }
            while(jobs[count][0] <= time) {
                pq.push(make_pair(jobs[count][1], jobs[count][0]));
                count++;
                if(count >= jobs.size()) {
                    break;
                 }
            }
        }
        
    }
    
    return averagetime / count;
}
```

진짜 좀 어이없었던 문제..
문제 조건이 헷갈려서 많이  헷갈렸다.
애초에 주어진 배열이 나는 순서대로인줄 알았고,
디스크에 없을때는 index0에 있는 값이 무조건 제일먼저 처리된다고 봤다.
하지만 그게 아니었다, [0,4] , [0,3], [0,2], [0,1] 인 경우, 0부터 처리하면 절대 안된다.
그래서 처음부터 jobs의 벡터를 sort해줬다.

우선순위큐를 이용했고, 생각보다 여러 방면으로 예외처리하는 게 어려웠던 문제였다.
그래서 조건들이 많았고.
우선순위큐에서는 각 작업이 끝난 직후의 time에 그 전에 혹은 지금 들어온 작업들을 다 push해줬다.
그 시점 time에 대해서는 들어온 작업 중에 제일 짧은 작업부터 먼저 처리해야 한다.
그다음, pop은 하나씩하면서 time이 지속되고, pop이 한번씩 발생할때마다 작업이 또 들어오니까 push하는 반복문을 또 그 안에 넣어줬다.
그리고, 각 작업이 이어지지 않은 경우는, 제일 먼저 조건걸어 time을 다시 선언했다.

시간복잡도는 push하는데 시간이 걸리므로,
O(nlogn)이라고 할 수 있다.

**Comment by Minimoa** [comment]
## solving point 

소요시간이 짧은 것을 먼저 처리해야한다. 

last  = 들어간 시점

now = 나오는 시점

이 사이에 있는 jobs의 소요시간을 heap에 넣는다 (작업 시간이 짧은 것 먼저 꺼내기 위해서)

이때 heap에 담기 전에 now에서 그 작업이 들어온 시점까지의 시간을 계산해서 더해준다



만약 수행되고 있는 작업이 있는 경우 해당 작업의 소요 시간 만큼 기다려야하기 때문에 len(heap)*heap[0] 해준다 

C가 수행되는 동안에 B가 이미 들어와있어서 같이 대기를 해야 하므로 C의 수행시간만큼 B가 대기 하게 된다. 



위의 방법은 아래 처럼 시점을 3가지로 쪼개서 더하는 것이다. 

1. 현재 시간부터 해당 작업이 시작되는 시간
2. 해당 작업의 소요 시간  
3. 대기 중인 작업의 대기 시간 

 

1은 위의 for문에서,  2+3의 값은  if문에서 answer에 더한다.

## python

```python
import heapq
def solution(jobs): 
    answer = 0
    last = -1 
    now = 0
    task = []
    n = len(jobs)
    cnt = 0
    
    while cnt < n :
        for j in jobs:
            if last< j[0] <= now :
                answer += (now-j[0])
                heapq.heappush(task,j[1])
            
        if len(task) > 0 :
            answer += len(task)* task[0]
            last = now 
            now += heapq.heappop(task)
            cnt += 1
        else :
            now += 1
    return answer // n
```



## C++

```c++
#include <string>
#include <vector>
#include <queue> 
using namespace std;

int solution(vector<vector<int>> jobs) {
    int answer = 0;
    int last = -1;
    int now = 0;
    priority_queue<int,vector<int>, greater<int>> task;
    int cnt = 0;
    int len = jobs.size();
    
    while(cnt<len){
        for(int i=0;i<jobs.size();i++){
            vector<int> cur = jobs[i];
            if (last < cur[0] && cur[0] <= now){
                answer += (now - cur[0]); 
                task.push(cur[1]);
            }
        }
        
        if(!task.empty()){ 
            answer += task.size() * task.top();
            last = now;
            now += task.top();
            task.pop();
            cnt += 1;
        }else{
            now+=1;
        }
    } 
    return answer/len;
}
```

c++의 우선순위큐는 최대힙이기때문에 greater로 정렬해 최소힙을 만들었다. 



소요시간이 짧은 것부터 처리해야하므로 최소힙을 만들어야겠다는 아이디어는 떠올렸는데 그 뒤로 

`하드디스크가 작업을 수행하고 있지 않을 때에는 먼저 요청이 들어온 작업부터 처리합니다.` 이 조건 때문에 엄청 헤맸다. 현재 시점 이전에 작업 요청이 있으면 소요시간이 짧은 순으로 처리하고 그 외에 경우에는 요청 시간 순으로 처리해야겠다는 생각에 다른 아이디어를 떠올리지 못한 것 같다. 솔직히 아직도 잘 모르겠고 저게 제일 효율적인 방법인 것 같아서 정리했다. 

범위를 정해서 그 사이에 값들을 넣는 다는 아이디어는 내가 떠올리지 못한 부분이기 때문에 기억해뒀다가 다른 문제에 활용하면 좋을 것 같다.
