### ISSUE TITLE
가장 큰 수

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#25]
문제 설명
0 또는 양의 정수가 주어졌을 때, 정수를 이어 붙여 만들 수 있는 가장 큰 수를 알아내 주세요.

예를 들어, 주어진 정수가 [6, 10, 2]라면 [6102, 6210, 1062, 1026, 2610, 2106]를 만들 수 있고, 이중 가장 큰 수는 6210입니다.

0 또는 양의 정수가 담긴 배열 numbers가 매개변수로 주어질 때, 순서를 재배치하여 만들 수 있는 가장 큰 수를 문자열로 바꾸어 return 하도록 solution 함수를 작성해주세요.

제한 사항
- numbers의 길이는 1 이상 100,000 이하입니다.
- numbers의 원소는 0 이상 1,000 이하입니다.
- 정답이 너무 클 수 있으니 문자열로 바꾸어 return 합니다.

**Comment by rose6649** [comment]
```cpp
#include <string>
#include <vector>
#include <queue>
#include <algorithm>

using namespace std;

bool com(const string a, const string b) {
    return a + b > b + a;
}

string solution(vector<int> numbers) {
    string answer = "";
    vector<string> v;
    for(int i=0; i<numbers.size(); i++) {
        string s = to_string(numbers[i]);
        v.push_back(s);
    }
    sort(v.begin(), v.end(), com);
    for(int i=0; i<v.size(); i++) {
        answer += v[i];
    }
    if(answer[0] == '0') {
        return "0";
    }
    
    return answer;
}
```

i dont like this .....
진짜 바보.. 나 자신 바보...
생각을 좀 간단하게 하면 금방 풀 문제였다.
일단 sort함수 자체가 nlogn 이기도 하고,
여기서 n이 100,000이니까..
시간복잡도 생각하다 골머리 터진문제.

100,000 * log2 100000
2의 17승 정도니까..
한 n*17 정도라고 생각하면 되겠다. 
n의 2승으로 풀었던 버블 소트는 당연 시간초과 났고 (백억이니까 - 보통 1억번당 1초라고 생각)
radix sort로 풀라했더니 또 자릿수가 나를 힘들게했고.
그래서 쉽게 생각을 바꾸니 됐다.

이상하게 시간 엄청 질질 끈 문제...너무 예외변수들을 많이 생각한 탓이다. ;;

**Comment by Minimoa** [comment]
가장 큰 수를 어떻게 만들면 좋을지 고민했다. 자릿수가 1인 것은 내림차순으로 정렬하고 나머지 중에서 만약 첫번째 숫자가 같으면 어쩌구 ... 도저히 어떻게 구현할지 감히 안 잡혀서 풀이를 찾아봤다.



## Python 

```python
def solution(numbers):
    answer = ''
    numbers = list(map(str,numbers))
    numbers.sort(key= lambda x: x*3, reverse = True)
    
    return str(int(''.join(numbers)))
```

key를 lamda 함수를 이용해 정렬한다. 각 숫자를 문자로 만든 후에 3개씩 이어 붙여서 정렬하는 것이다. 3개씩 이어 붙이는 이유는 각 원소가 1,000 이하이기 때문.

 따라서 `[3, 30, 34, 5, 9]` 경우 `333, 303030, 343434, 555, 999` 를 가지고 정렬하게된다. 

문자열의 정렬은 ASCII 값으로 치환되어 정렬되는데 각 문자의 첫번째 인덱스 값으로 비교하게된다. 

그러면 `1=81 2= 82 3= 83 ... 9= 89` 이고  python sort는 오름차순이 기본이기 때문에 `reverse = True`로 내림차순 정렬하면 ` ['9', '5', '34', '3', '30']` 이 된다. join으로 하나로 묶은 다음 int -> string으로 변환한다. 

int를 거치는 이유는 0000일 경우 0으로 반환해야하기 때문이다. 



## C++

마찬가지로 문자로 변환한것을 3개씩 이어 붙여 비교 정렬한다. 

```c++
#include <string>
#include <vector> 
#include <algorithm>

using namespace std;

bool cmp(const string &a, const string &b){
    return a+a+a> b+b+b;
}
string solution(vector<int> numbers) {
    string answer = ""; 
    vector<string> tmp;
    for(auto n : numbers){
        tmp.push_back(to_string(n));
    }
    
    sort(tmp.begin(),tmp.end(),cmp);
    
    for(auto a : tmp)
        answer+= a;
    
    if(answer[0] == '0')
        return "0";
    return answer;
}
```
