### ISSUE TITLE
H-Index

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#26]
문제 설명
H-Index는 과학자의 생산성과 영향력을 나타내는 지표입니다. 어느 과학자의 H-Index를 나타내는 값인 h를 구하려고 합니다. 위키백과1에 따르면, H-Index는 다음과 같이 구합니다.

어떤 과학자가 발표한 논문 n편 중, h번 이상 인용된 논문이 h편 이상이고 나머지 논문이 h번 이하 인용되었다면 h의 최댓값이 이 과학자의 H-Index입니다.

어떤 과학자가 발표한 논문의 인용 횟수를 담은 배열 citations가 매개변수로 주어질 때, 이 과학자의 H-Index를 return 하도록 solution 함수를 작성해주세요.

제한사항
- 과학자가 발표한 논문의 수는 1편 이상 1,000편 이하입니다.
- 논문별 인용 횟수는 0회 이상 10,000회 이하입니다.

**Comment by rose6649** [comment]
```cpp
#include <string>
#include <vector>
#include <queue>
#include <algorithm>

using namespace std;

int solution(vector<int> citations) {
    int answer = 0;
    int count = 0;
    sort(citations.begin(), citations.end(), greater<int>());

    for(int i=0; i< citations.size(); i++){
        count++;
        if(i+1 >= citations[i]){
            if(i+1 > citations[i]) count = i;
            else count = i+1;
            break;
        }
    }
    answer = count;
    return answer;
}
```

음.. 뭔가 이상하게 시간 엄청 끈 문제.
굉장히 쉽게 sort로 생각하면 빨리 풀 문제였다.
근데 문제가 뭔가 되게 이해하기 어려웠던건 내 머리를 탓해야겠지...
암튼 기본적으로  h의 최댓값을 찾는 문제였다.
그래서 내림차순 정렬을 이용했고,
그래야 큰 수부터 비교연산을 하며 counting 을 할 수 있기 때문이다.
만약에 index+1 횟수와 값이 같다면 그 count를 넣어주면 되고,
index+1 횟수보다 값이 크면, counting 횟수값을 넣어주면 된다.
index+1  횟수보다 값이 작으면, 그 index값을 넣어주면된다.

**Comment by Minimoa** [comment]
전체 논문 중 많이 인용된 순으로 정렬한 후 인용횟수가 논문수와 같아지거나 작아지기 시작하는 숫자 ?남은 논문수가 인용수보다 같거나 작아지는 숫자라더니 



## Python 

```python
def solution(citations):
    answer = 0
    citations.sort(reverse = True)  
    n = 0 
    while citations :    
        n+=1
        c = citations.pop(0)
        if c <= n :
            return c
    return answer
```



왜 틀렸는지조차 모르겠음; 애초에 문제 이해를 못했음



인용횟수를 정렬한 후 해당 횟수 이상인 논문의 수가 해당회수와 일치하는 지점을 찾아야함 

```python
def solution(citations):
    answer = 0
    citations.sort()
    n = len(citations) 
    
    for i in range(n):
        if citations[i] >= n-i:
            return n-i
    return answer
```





## C++

```c++
#include <string>
#include <vector>
#include <algorithm>

using namespace std;

int solution(vector<int> citations) {
    int answer = 0;
    sort(citations.begin(),citations.end());
    int n = citations.size();
    
    for(int i=0;i<citations.size();i++){
        if(citations[i] >= n-i)
            return n-i;
    }
    return answer;
}
```

흑흑
