### ISSUE TITLE
소수 찾기

### ISSUE THREAD

**Issue by Minimoa** [Minimoa/1-day-1-algorithm#28]
한자리 숫자가 적힌 종이 조각이 흩어져있습니다. 흩어진 종이 조각을 붙여 소수를 몇 개 만들 수 있는지 알아내려 합니다.

각 종이 조각에 적힌 숫자가 적힌 문자열 numbers가 주어졌을 때, 종이 조각으로 만들 수 있는 소수가 몇 개인지 return 하도록 solution 함수를 완성해주세요.

제한사항
numbers는 길이 1 이상 7 이하인 문자열입니다.
numbers는 0~9까지 숫자만으로 이루어져 있습니다.
013은 0, 1, 3 숫자가 적힌 종이 조각이 흩어져있다는 의미입니다.

numbers | return
-- | --
17 | 3
011 | 2

**Comment by rose6649** [comment]
```cpp
#include <string>
#include <vector>
#include <algorithm>

using namespace std;

#define MAX 10000000

vector<int> arr;
bool prime[MAX];
bool check[MAX];
bool visit[7];
int answer = 0;



void dfs(int value, int digit) {
    if(digit == arr.size()) {
        if(!(prime[value])) {
            if(!(check[value])) answer++; 
            check[value] = true;
        }
        return;
    }
    
    for(int i=0; i<arr.size(); i++) {
        if(visit[i]) continue;
        visit[i] = true;
        if(!(prime[value])) {
            if(!(check[value])) answer++; 
            check[value] = true;
        }
        int number = value * 10 + arr[i];
        dfs(number, digit+1);
        visit[i] = false;
    }
    
}

void isPrime() {
    for(int i=2; i<MAX; i++) {
        if(prime[i]) continue;
        for(int j=2; i*j<MAX; j++) {
            prime[j*i] = true;
        }
    }
    prime[1] = true;
    prime[0] = true;
}

int solution(string numbers) {
    for(int i=0; i<numbers.length(); i++) {
        int num = numbers[i] -'0';
        arr.push_back(num);
    }
    
    isPrime();
    
    for(int i=0; i<arr.size(); i++) {
        visit[i] = true;
        dfs(arr[i], 1);
        visit[i] = false;
    }
    
    return answer;
}
```

여러가지 방법들이 많겠지만 일단 소수는 1-7자리의 수를 한번에 다 구하는게 빠르므로, 에라토스(?) 뭐시기의 체를 이용하여 일단
소수값들은 미리 따로 값을 빼줬다.
그리고나서 문제는 순열인데, 대부분 next_permutiation인가 그런 함수를 이용하여 풀던데,
나는 그런거 잘 라이브러리를 이용하는데 기억을 못해서 그냥 내가 알고있는 지식으로 dfs로 재귀함수 짰다.
함수가 계속 반복되어야 할 시점을 생각을 해보면, 항상 visit 배열이 존재했던것 같다.
이 수는 내가 이미 방문했으므로, 건너뛰고 가는것이다.
그리고 자릿수를 하나씩 더해주면서 늘려간다. 그렇게되면, 결국 마지막에 수의 최장길이에서 리턴한다. (이 경우의 수들은 다 돌았으므로)
오랜만에 dfs  이용하자니, 머리가 아팠다.
순열과 조합은 항상 생각하는데 복잡하니, 이것도 조금 더 능력을 키워야할 것 같다.

소수찾는 부분의 함수는 n^2 이고, dfs는 순열이니까, n! 로 계산해야할것같다.

**Comment by Minimoa** [comment]
`itertools`의 `permutations` 라이브러리를 사용해 가능한 모든 순열을 구한 후 

소수인지 판별하여 set에 담아 총 갯수를 리턴한다. 

## python

```python
from itertools import permutations
 
def is_prime(x): 
    if x<2 :
        return False
    for i in range(2,int(x**0.5)+1):
        if x % i == 0 :
            return False
    return True

def solution(numbers): 
    prime_set = set()
    for i in range(len(numbers),0,-1):
        for n in list(map(int,map(''.join, permutations(numbers,i)))):
            if is_prime(n):
                prime_set.add(int(n))  
    return len(prime_set)
```



### itertools

- `permutations(iterable,r)`

  iterable 객체에서 r개의 데이터를 뽑아 일렬로 나열하는 모든 경우(순열)을 계산해 문자열 튜플 형태로 리턴해준다.

- `combinations`

  iterable 객체에서 r개의 데이터를 뽑아 순서를 고려하지 않고 나열하는 모든 경우(조합)을 계산해 문자열 듀플 형태로 리턴해준다. 

- `product(data,repeat)`

  `permutations`와 같이 순열이지만 중복을 허용하여 뽑는다. 클래스이기 때문에 객체 초기화 이후에는 리스트로 변환하여 사용하고, 객체 초기화시에는 뽑고자하는 데이터 수를 reapeat에 넣어 준다 

- `combinations_with_replacement(data,repeat)`

  `combinations`와 같이 조합이지만 중복을 허용하여 뽑는다. 클래스이기 때문에 객체 초기화 이후에는 리스트로 변환하여 사용하고, 객체 초기화시에는 뽑고자하는 데이터 수를 reapeat에 넣어 준다 



순열 조합 문제에서 유용하게 쓸 수 있는 라이브러리이므로 꼭 기억해두기!





### 소수 판별 

- **2 ~ (x-1) 수로 나눠지지 않으면 소수이다.** 

  ```python
  def is_prime(n):
  	if n < 2 :
  		return False
      for i in range(2,x):
          if n % i == 0 :
          	 return False
      return True
  ```

  <u>o(n) 으로 비효율적임</u>

- **2 ~ sqrt(x) 수로 나눠지지 않으면 소수이다.** 

  어떤 수의 최대 공약수의 순열은 제곱근을 기준으로 대칭이다. 따라서 제곱근 전까지만 나눠지는지 확인하면된다. 

  ```python
  def is_prime(n):
      if n <2 :
          return False
      for i in range(2, int(x**0.5)+1): #range 안에는 정수만 들어갈 수 있음
          if n % i == 0:
              return False
      return True
  ```

  o(n^0.5) 로 시간 복잡도가 개선됨

- **에라토스테네스의 체** 

  2~n 까지 가능한 모든 수를 나열한 후 더이상 반복할 수 없을때 까지 남은 수 중에서 아직 처리하지 않은 가장 작은 수 i를 찾아 i를 제외한  i의 배수를 모두 제거한다.

  가장 작은 수 i 역시 제곱근까지만 확인하면 된다.  

  ```python
  n= 1000
  #처음에는 모두 소수인 것으로 초기화 (0,1은 제외)
  array = [True for i in range(n+1)] 
  
  #에라토스테네스의 체
  for i in range(2, int(n**0.5)+1): # 2~ n 제곱근까지
      if array[i] == True : #i가 남은 수일 경우 
  		j = 2
  		while i*j <= n: #i를 제외한 i의 모든 배수 지우기
  			array[i*j] = False
  			j+=1
          
  #모든 소수 출력
  for i in range(2,n+1):
      if array[i]:
          print(i,end=' ')
  ```

  O(NloglogN)으로 선형 시간 정도로 굉장히 빠르다. 단점은 메모리가 많이 필요함

  

에라토스테네스의 체를 활용한 다른 사람 풀이

```python
from itertools import permutations
def solution(n):
    a = set()
    for i in range(len(n)):
        a |= set(map(int, map("".join, permutations(list(n), i + 1))))
    a -= set(range(0, 2))
    for i in range(2, int(max(a) ** 0.5) + 1):
        a -= set(range(i * 2, max(a) + 1, i))
    return len(a)
```

set의 특징을 활용했다. 

`(range(i * 2, max(a) + 1, i)`  은 `i*2`에서 i씩 증가하니까 결국 i의 배수와 같다 



## C++

c++ 진짜 왤케 복잡하냐고 

```c++
#include <string>
#include <vector>
#include <algorithm> 
#include <cmath> 

using namespace std;
 
int solution(string numbers) {
    int answer = 0;   
    int array[10000000] = {0,};
    sort(numbers.begin(),numbers.end(),greater<int>());
    int number = stoi(numbers); 
    
    //에라토스테네스의 체
    for(int i=2;i < sqrt(number);i++){ 
        if(array[i]==0){
            int j = 2;
            while (i*j <= number){
                array[i*j] = 1;
                j+=1;
            }
        }
    }
    
    
    //소수와 numbers 비교 
    for(int i=2;i<=number;i++){
        if(array[i] == 0){
            int cnt = 0;
            string tmp = to_string(i); 
            char copied[8];
            numbers.copy(copied,sizeof copied-1);
            copied[numbers.size()] = '\0';
                
            for(int x=0;x<tmp.size();x++){
                for(int y=0;y<8;y++){
                    if(tmp[x] == copied[y]){
                        copied[y] = -1; 
                        cnt ++;
                        break;
                    }
                }
            }
            
            if(cnt == tmp.size()) 
                answer++; 
        }
    }
    
    return answer;
}
```



파이썬과 마찬가지로 가능한 모든 순열 조합을 나열해서 소수를 구하려다가 도저히 안되서 범위 내의 가능한 모든 소수를 구했다. numbers 내림차순 정렬하면 만들 수 있는 가장 큰 수가 나오므로 2~ number 내림차순 수 범위 내에서 에라토스테네스의 체로 가능한 모든 소수를 구한 후, numbers와 소수를 하나 하나 비교해서 numbers로 만들 수 있는 소수이면 answer을 카운트했다. 



**헤맸던 점** 

1. sqrt 

   sqrt 는 기본으로 쓸 수 있는 줄 알았는데 cmath안에 있었다. 

2. 배열 초기화 

   0외에 다른 수로 초기화하면 첫번째 원소만 초기화된다는 걸 까먹음

3. string은 수정 불가 배열처럼 수정 불가  

4. string - > char[]  복사

   ` numbers.copy(copied,sizeof copied-1);`

5. 소수와 numbers의 비교시 중복 제거 

   이미 비교한 원소는 -1로 바꿔서 또 비교 되지 않도록 했다. 이거 때문에 numbers의 복사가 필요했다. 그리고 같은 경우에는 break로 빠져나가서 뒤의 원소와 비교되지 않도록 하는 게 필요했다. 

6. `segmentation fault (core dumped)`

   두 개의 테스트 케이스에서 `segmentation fault (core dumped)`가 떠서 멘붕이었는데 메모리 문제였다. 7자리 이하이므로 7자리를 감당할 수 있는 크기로 array를 만들어야하는데 1000,000 로 선언해서 오류가 났고 100,000,000 로 수정해 해결했다.
