### ISSUE TITLE
카펫

### ISSUE THREAD

**Issue by Minimoa** [Minimoa/1-day-1-algorithm#29]
Leo는 카펫을 사러 갔다가 아래 그림과 같이 중앙에는 노란색으로 칠해져 있고 테두리 1줄은 갈색으로 칠해져 있는 격자 모양 카펫을 봤습니다.
 
![image](https://user-images.githubusercontent.com/13061461/105788959-d6fbff80-5fc4-11eb-9f28-9235b9c5f2b1.png)

Leo는 집으로 돌아와서 아까 본 카펫의 노란색과 갈색으로 색칠된 격자의 개수는 기억했지만, 전체 카펫의 크기는 기억하지 못했습니다.

Leo가 본 카펫에서 갈색 격자의 수 brown, 노란색 격자의 수 yellow가 매개변수로 주어질 때 카펫의 가로, 세로 크기를 순서대로 배열에 담아 return 하도록 solution 함수를 작성해주세요.

제한사항
갈색 격자의 수 brown은 8 이상 5,000 이하인 자연수입니다.
노란색 격자의 수 yellow는 1 이상 2,000,000 이하인 자연수입니다.
카펫의 가로 길이는 세로 길이와 같거나, 세로 길이보다 깁니다.

brown | yellow | return
-- | -- | --
10 | 2 | [4, 3]
8 | 1 | [3, 3]
24 | 24 | [8, 6]

**Comment by rose6649** [comment]
```cpp
#include <string>
#include <vector>

using namespace std;

vector<int> solution(int brown, int yellow) {
    vector<int> answer;
    int total = brown + yellow;
    int count = 0;
    for(int i=total; i>0; i--) {
        if(total % i == 0) {
            int j = total / i;
            if(i < j) break;
            int brownTotal = (i*2)+(j*2)-4;
            if(brownTotal == brown) {
                answer.push_back(i);
                answer.push_back(j);
                break;
            }
        }
    }
    return answer;
}
```

내가 제일 싫어하는 소수찾기를 제쳐두고..
먼저풀었다. 비교적 엄청 쉽게 나온다.
음, 최대공약수를 가로순이 높을때까지만 비교한다.
시간복잡도는 O(n)이다.

**Comment by Minimoa** [comment]
최대 공약수를 구해서 둘레 길이가 brown과 일치하고 가로가 세로보다 크거나 같은 수를 찾는다.



## python

```python
def solution(brown, yellow):
    answer = []
    total = brown + yellow
    
    for i in range(total-1,0,-1):  
        j = total//i  
        if i>=j and total % i == 0 :
            perimeter = (i*2)+(j*2)-4 
            if perimeter == brown:
                answer.append(i)
                answer.append(j)
                break
    return answer
```





## c++

```c++
#include <string>
#include <vector>

using namespace std;

vector<int> solution(int brown, int yellow) {
    vector<int> answer;
    int total = brown + yellow;
    
    for(int i=total;i>0;i--){
        if(total % i == 0 ){
            int j = total/i;
            int p = (i*2)+(j*2)-4;
            if(i>=j && p == brown){
                answer.push_back(i);
                answer.push_back(j);
                break;
            }
        }
    }
    return answer;
}
```





방정식을 세워서 푸는 방법도 있다. 

```c++
x*y = brown + yellow
(x-2)(y-2) = yellow	
```

이므로 근의 공식을 사용해 풀기도 하더라 ..
![image](https://user-images.githubusercontent.com/13061461/106110437-0f9b0500-618e-11eb-9b5b-e7f1679c2434.png)
![image](https://user-images.githubusercontent.com/13061461/106110454-16297c80-618e-11eb-9208-3249ca65ced1.png)
