### ISSUE TITLE
체육복

### ISSUE THREAD

**Issue by rose6649** [Minimoa/1-day-1-algorithm#31]
문제 설명
점심시간에 도둑이 들어, 일부 학생이 체육복을 도난당했습니다. 다행히 여벌 체육복이 있는 학생이 이들에게 체육복을 빌려주려 합니다. 학생들의 번호는 체격 순으로 매겨져 있어, 바로 앞번호의 학생이나 바로 뒷번호의 학생에게만 체육복을 빌려줄 수 있습니다. 예를 들어, 4번 학생은 3번 학생이나 5번 학생에게만 체육복을 빌려줄 수 있습니다. 체육복이 없으면 수업을 들을 수 없기 때문에 체육복을 적절히 빌려 최대한 많은 학생이 체육수업을 들어야 합니다.

전체 학생의 수 n, 체육복을 도난당한 학생들의 번호가 담긴 배열 lost, 여벌의 체육복을 가져온 학생들의 번호가 담긴 배열 reserve가 매개변수로 주어질 때, 체육수업을 들을 수 있는 학생의 최댓값을 return 하도록 solution 함수를 작성해주세요.

제한사항
- 전체 학생의 수는 2명 이상 30명 이하입니다.
- 체육복을 도난당한 학생의 수는 1명 이상 n명 이하이고 중복되는 번호는 없습니다.
- 여벌의 체육복을 가져온 학생의 수는 1명 이상 n명 이하이고 중복되는 번호는 없습니다.
- 여벌 체육복이 있는 학생만 다른 학생에게 체육복을 빌려줄 수 있습니다.
- 여벌 체육복을 가져온 학생이 체육복을 도난당했을 수 있습니다. 이때 이 학생은 체육복을 하나만 도난당했다고 가정하며, 남은 체육복이 하나이기에 다른 학생에게는 체육복을 빌려줄 수 없습니다.

**Comment by rose6649** [comment]
```cpp
#include <string>
#include <vector>

using namespace std;

int solution(int n, vector<int> lost, vector<int> reserve) {
    int answer = 0;
    int total[n+1];
    int max[n+1];
    
    fill_n(total, n+1, 1);
    
    for(int i=0; i<lost.size(); i++) {
        total[lost[i]]--;
    }
    
    for(int i=0; i<reserve.size(); i++) {
        total[reserve[i]]++;
    }
    
    for(int i=1; i<=n; i++) {
        if(total[i] == 1) {
            answer++;
        }
        else if(total[i] == 0) {
            if(total[i-1] == 2) answer++;
            else if(total[i+1] == 2) {
                answer++;
                total[i+1]--;
            }
        }
        else if(total[i] == 2) answer++;
    }
    
    return answer;
}
```

level1문제라 간단히 푼 문제.
total의 인덱스값으로,
0 : 체육복 없음
1 : 체육복 자기것만 있음
2 : 여분있음
으로 비교하고, 맨처음부터 마지막까지 순서대로 비교하여
여분이있는 학생이 없는 학생에게 빌려주며 answer값을 올린다.

탐욕법이면, 계속된 최적해를 푸는 문제인데, 여기서는 딱히 그리디문제라고 느껴지지 않았다.

**Comment by Minimoa** [comment]
## python

서로 겹치는 원소를 제거한다 

reserve의 원소에서 +1,-1한 값이 lost에 있으면 제거한다 

lost 길이를 n에서 빼서 리턴한다

set의 차집합을 활용했다. 서로 겹치는 원소를 뺀다음 reserve에서 -1또는 +1한 값이 lost에 있으면 제거했다.

```python
def solution(n, lost, reserve):
    answer = n  
    
    ls = list(set(lost) - set(reserve))
    rs = list(set(reserve) - set(lost))
    
    for r in rs:
        for l in ls:
            if r+1 == l or r-1 == l:
                ls.remove(l)
                break 
                
    answer -= len(ls)
    return answer

```





## C++

희주꺼 참고

인덱스를 활용해서 계산하는 방법

`fill_n` 함수라는게 있는지 처음 알았다 

```c++
#include <string>
#include <vector> 

using namespace std;

int solution(int n, vector<int> lost, vector<int> reserve) {
    int answer = 0; 
    int total[n+1];
    
    fill_n(total,n+1,0);
    for(int r: reserve) total[r] += 1;
    for(int l: lost) total[l] -= 1;
    
    for(int i=1; i<=n;i++){
        if(total[i] == -1){
            if(total[i-1] == 1)
                total[i-1] = total[i] = 0;
            else if(total[i+1] == 1)
                total[i+1] = total[i] = 0;
        }
    }
    
    for(int i  = 1; i <=n; i++)
        if(total[i] != -1) answer++; 
    return answer;
}
```





파이썬 라이브러리가 너무 편해서 기본 실력은 줄어드는 느낌 ;

C++에서 범위 기반 for문을 남발하지말자 항상 통하는게 아님
