### ISSUE TITLE
큰 수 만들기

### ISSUE THREAD

**Issue by Minimoa** [Minimoa/1-day-1-algorithm#33]
어떤 숫자에서 k개의 수를 제거했을 때 얻을 수 있는 가장 큰 숫자를 구하려 합니다.

예를 들어, 숫자 1924에서 수 두 개를 제거하면 [19, 12, 14, 92, 94, 24] 를 만들 수 있습니다. 이 중 가장 큰 숫자는 94 입니다.

문자열 형식으로 숫자 number와 제거할 수의 개수 k가 solution 함수의 매개변수로 주어집니다. number에서 k 개의 수를 제거했을 때 만들 수 있는 수 중 가장 큰 숫자를 문자열 형태로 return 하도록 solution 함수를 완성하세요.

제한 조건
number는 1자리 이상, 1,000,000자리 이하인 숫자입니다.
k는 1 이상 number의 자릿수 미만인 자연수입니다.

number | k | return
-- | -- | --
1924 | 2 | 94
1231234 | 3 | 3234
4177252841 | 4 | 775841

**Comment by Minimoa** [comment]
앞 자리에 큰 수가 오는 것이 전체를 크게 만든다 

큰 것을 우선해서 앞자리에 넣어야한다. 

앞 자리에 오는 작은 수들을 지워줘야한다. 



앞자리부터 스택에 넣고 다음으로 넣으려는 수가 들어있는 수보다 클 경우 모두 꺼내서 지운다 

ex) 4177~ 

[4,1] <-- 7     ----> [7]

단 k만큼만 빼야한다 



만약 작은 수가 뒤에 몰려 있을 경우 

ex)  number = 98765,  k = 2

뒤에 숫자 2개를 지워주면된다. 



## python

**처음 풀이**

```python
def solution(number, k):
    answer = [0 for _ in range(len(number))]
    numbers = [[int(n),i] for i,n in enumerate(number)]
    tmp = []  
    
    
    while len(tmp) < (len(number)-k) :  
        _max = max(numbers) 
        numbers[_max[1]] = [-1,-1] 
        
        tmp.append(_max)
    
    for t in tmp :
        answer[t[1]] = t[0]
    
    final = ""
    for a in answer:
        if a != 0 :
            final += str(a)
            
    return final
```

처음에는 조합을 생각했다. 가능한 모든 조합을 정렬해서 가장 큰 값을 꺼내려는 가장 무식한 방법이어서 당연히 시간 초과가 났다. 

다음으로는 각 숫자들을 크기 순으로 뽑아서 자리에 채워 넣어 만드는 방법을 생각했는데 만약 앞에 있는 수가 범위에 걸릴 경우 거를 수 없는 방법이 없었다. 

 값을 만날때까지 앞의 작은 수들을 삭제해야겠다는 생각은 했는데 어떻게 구현해야할지 몰랐다.



**최종**

```python
def solution(number, k):
    answer = []
    
    for n in number:
        while len(answer) > 0 and answer[-1] < n and k > 0:
            answer.pop()
            k -= 1 
        answer.append(n)
    
    if k != 0 :
        answer = answer[:-k]
    return "".join(answer)
```

스택을 이용하는 방법이 있었다. 

큰 수를 만나기 전까지는 스택에 다 넣고 큰 수를 만나면 다 꺼낸다 그렇게 하고나면 내림차순으로 숫자가 쌓이게된다. 비교는 맨 마지막 원소만 하면된다 

작은 수가 뒤쪽에 몰려있는 예외 사항이 있으므로 만약 k를 다 채우지 못했으면 그만큼 뒤를 잘라주면 된다. 

최악의 경우라 하더라도 while문이 n-1만큼 도는 경우는 1번 밖에 없으므로 O(n)이다. 



## C++

```c++
#include <string>
#include <vector>
#include <stack>
#include <algorithm>

using namespace std;

string solution(string number, int k) {
    string answer = "";
    stack<int> tmp;
    
    for(char n : number){
        while(!tmp.empty() && tmp.top() < n && k > 0 ){
            tmp.pop();
            k--;
        }
        tmp.push(n);
    }
    
    if(k!= 0){
       for(int i=0;i<k;i++){
           tmp.pop();
       }
    }
    
    while(!tmp.empty()){
        answer += tmp.top();
        tmp.pop();
    }
    reverse(answer.begin(),answer.end());
    return answer;
}
```



똑같은 논리로 풀었고 C++의 경우에는 배열을 하나로 합치는 게 없어서 하나씩 붙인 다음 뒤집었다. (stack 이라서 )

**Comment by rose6649** [comment]
```cpp
#include <string>
#include <vector>
#include <queue>
#include <algorithm>

using namespace std;

string solution(string number, int k) {
    string answer = "";
    int arr[number.length()];
    
    for(int i=0; i<number.length(); i++) {
        int num = number[i] - '0';
        arr[i] = num;
    }
    
    int index = number.length() - k;
    int start = 0, startindex = 0;
    int end = k, endindex = k;
    int stringnum[index];
    int stringnumindex = 0;
    
    fill_n(stringnum, index, -1);
    //글자수만큼
    for(int i=0; i<index; i++) {
        start = startindex;
        end = endindex;
        for(int j=start; j<=end; j++) {
            if(stringnum[stringnumindex] < arr[j]) {
                stringnum[stringnumindex] = arr[j];
                startindex = j+1;
            }
        }
        stringnumindex++;
        endindex++;
    }
    
    for(int i=0; i<index; i++) {
        answer += to_string(stringnum[i]);
    }
    
    return answer;
}
```

음.. 레벨2에 맞는 문제.
우선 순서는 중요하다.
순서를 바꿀 수 없으므로, 각 자리의 위치를 벗어나면안된다.
그 중에서, 배열을 이용하여 풀었는데,
startindex와  endindex를 이용했다.

일단, 맨 처음 index에 있는 수가 클 수록, 클수밖에 없다.
그래서, k를 뺀 자릿수를 생각하고,
그 자릿수만큼 중에서 제일 큰 수를 한 자리씩 채워갔다.
각 범위내에서 제일 큰 수를 담아주면, 그 수가 최대가 된다.

O(n)정도 걸릴문제.
